version: "3.9"

services:
  postgresDB:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "NomNomNumbers"
      POSTGRES_USER: "NomNomNumbers"
      POSTGRES_DB: "NomNomNumbers"