CREATE TABLE IF NOT EXISTS USERS (
    ID BIGSERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS  ROLES (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
    USER_ID BIGSERIAL NOT NULL,
    ROLE_ID BIGSERIAL NOT NULL
);

CREATE TABLE IF NOT EXISTS INGREDIENTS (
    ID BIGSERIAL PRIMARY KEY ,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    PROTEIN FLOAT NOT NULL,
    FAT FLOAT NOT NULL,
    CARBOHYDRATES FLOAT NOT NULL,
    CALORIES FLOAT NOT NULL,
    PRICE FLOAT
);

CREATE TABLE IF NOT EXISTS MEALS (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MEALS_INGREDIENTS (
    MEAL_ID BIGSERIAL REFERENCES MEALS(ID) ON DELETE CASCADE,
    INGREDIENT_ID BIGSERIAL REFERENCES INGREDIENTS(ID),
    AMOUNT BIGSERIAL NOT NULL,
    PRIMARY KEY (MEAL_ID, INGREDIENT_ID)
);